try {
  // Some code that might throw an error
} catch (e) {
  console.log("Error:", e);
}
